[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "sans serif"

[server]
maxUploadSize = 2048
enableXsrfProtection = true
enableCORS = false

[browser]
gatherUsageStats = false
